name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  job1:
    uses: lfraileorg/reusable-workflows/.github/workflows/reusable-workflow.yml@main
    with:
      username: lfraile
    secrets:
      token: ${{ secrets.FOO_TOKEN }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.output1 }} ${{ needs.job1.outputs.output2 }}
